#
# For documentation see https://codecov.io/gh/twisted/twisted/settings/yaml
#
coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 90%

comment:
  layout: "header, diff, uncovered"
  behavior: default